#!/usr/bin/env bash
# 0. World wide web

get_ip() {
    address="$2.$1"
    ip=$(dig "$address" | grep -A1 'ANSWER SECTION:' | grep "$2" | awk '{print $5}')
    echo "The subdomain $2 is a A record and points to $ip"   
}

if [ $# -eq 1 ]; then
    get_ip "$1" "www"
    get_ip "$1" "lb-01"
    get_ip "$1" "web-01"
    get_ip "$1" "web-02"
elif [ $# -eq 2 ]; then
    get_ip "$1" "$2"
fi
