#!/usr/bin/env bash
# 1. Install nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html 2>> error.log
sudo service nginx restart
