#!/usr/bin/env bash
# 0. Double the number of webservers

sudo apt-get -y update
sudo apt-get -y install nginx

mkdir -p /var/www/html
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html 2>> error.log
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom404.html 2>> error.log

content=\
"
server {
    error_page 404 /custom404.html;
    location = /custom404.html {
        root /usr/share/nginx/html;
        internal;
    }

	listen 80 default_server;
	listen [::]:80 default_server;

    add_header X-Served-By $HOSTNAME;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;

    location /redirect_me {
        rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
    }

	location / {
		try_files $uri $uri/ =404;
	}
}
"

sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/
echo "$content" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
