#!/usr/bin/env bash
# This script is displaying Numbers 20 times except some iterations
i=0
while [ $i -ne 20 ]; do
	i=$((i + 1))
	echo $i
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
done
