#!/usr/bin/env bash
# This script is checking file format

file=school
if [ -e "$file" ]; then
	if [ -s "$file" ]; then
		echo "school file is not empty"
		if [ -f "$file" ]; then
			echo "school is a regular file"
		fi
	else
		echo "school file is empty"
	fi
else
	echo "school file does not exist"
fi
