#!/usr/bin/env bash
# 7 lines or less
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i -e 's%listen 80 default_server;%listen 8080 default_server;%' -e 's%listen \[::\]:80 default_server ipv6only=on;%listen [::]:8080 default_server ipv6only=on;%' -e 's%server_name localhost;%server_name _;%' /etc/nginx/sites-available/default
sudo pkill apache2 | sudo -u nginx service nginx restart > /dev/null 2>&1
