#!/usr/bin/env bash
# Write a Bash script that uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu.

private_key="~/.ssh/school"
remote_user="ubuntu"
remote_host="34.232.52.155"

ssh -i $private_key $remote_user@$remote_host
